import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Footer from '@/Components/Footer/Footer'
import Form from '@/Components/Form/Form'

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
        
      </Head>

      <main className={`${styles.main}`}>
          <div className={styles.container}>
            <Image className={styles.leftphoto} src={'/Image/leftphoto.png'}alt="instagram photo"width={380.31} height={581.15}priority/>
            
            <div className={styles.right_container}>
              <div className={styles.logo_login}> 
               <Image className={styles.iglogo} src={'/Image/instagram_logo.jpeg'}alt="Instagram logo" width={175} height={100}priority/>

               <Form/>
              </div>

              <div className={styles.right_container2}>
                <p className={styles.noAccount}>Don't have an account?<br></br><span className={styles.signup}>Sign up</span></p>
               </div>

              <div className={styles.right_container3}>
                <span className={styles.getapp}>Get the app.</span>
                <div className={styles.downloadapp}>
                  <Image src={'/Image/download_logo.png'}alt="Download on the app store or Google Play" width={270.28} height={44}/>
                </div>
              </div>
            </div>
          </div>
          <Footer/>      
      </main>
    </>
  )
}
